"""empty message

Revision ID: 4100401c1f32
Revises: 
Create Date: 2022-03-28 20:42:59.861611

"""
from alembic import op
import sqlalchemy as sa

import json
import os


# revision identifiers, used by Alembic.
revision = '4100401c1f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    years = op.create_table('year',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('number', sa.Integer(), nullable=True),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('number')
                            )
    with open(os.path.join(os.path.dirname(__file__), "../data/2022/year.json")) as f:
        year_data = f.read()
    op.bulk_insert(years, json.loads(year_data))
    op.create_index(op.f('ix_year_id'), 'year', ['id'], unique=False)

    states = op.create_table('state',
                             sa.Column('id', sa.Integer(), nullable=False),
                             sa.Column('name', sa.Text(), nullable=False),
                             sa.Column('income_tax', sa.Float(),
                                       nullable=False),
                             sa.Column('sales_tax', sa.Float(),
                                       nullable=False),
                             sa.Column('property_tax', sa.Float(),
                                       nullable=False),
                             sa.Column('year_id', sa.Integer(), nullable=True),
                             sa.ForeignKeyConstraint(
                                 ['year_id'], ['year.id'], ),
                             sa.PrimaryKeyConstraint('id')
                             )
    with open(os.path.join(os.path.dirname(__file__), "../data/2022/states.json")) as f:
        student_data = f.read()
    op.bulk_insert(states, json.loads(student_data))

    op.create_index(op.f('ix_state_id'), 'state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_id'), table_name='state')
    op.drop_table('state')
    op.drop_index(op.f('ix_year_id'), table_name='year')
    op.drop_table('year')
    # ### end Alembic commands ###
