"""empty message

Revision ID: be405615a999
Revises: 4100401c1f32
Create Date: 2022-04-01 15:41:41.983163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be405615a999'
down_revision = '4100401c1f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federal',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('year_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['year_id'], ['year.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_federal_id'), 'federal', ['id'], unique=False)
    op.create_table('tax_bracket',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tax_rate', sa.Float(), nullable=False),
                    sa.Column('bracket_start', sa.Integer(), nullable=False),
                    sa.Column('bracket_end', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('federal_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['federal_id'], ['federal.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tax_bracket_id'),
                    'tax_bracket', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_bracket_id'), table_name='tax_bracket')
    op.drop_table('tax_bracket')
    op.drop_index(op.f('ix_federal_id'), table_name='federal')
    op.drop_table('federal')
    # ### end Alembic commands ###
